graph LR
    N((Null)) -- Read Miss --> S
    N -- Write Miss --> M
    I((Invalid)) -- Read Miss --> S((Shared))
    S -- Read Hit --> S
    S -- Invalidate --> I
    S -- Write Hit --> M
    M((Modified)) -- Read Miss --> S
    I -- Write Miss --> M
    M -- Write / Read Hit --> M
    M -- Write Miss --> M
    M -- Invalidate --> I
